# Generated by Django 2.2.4 on 2022-06-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpass',
        ),
    ]
